list:
  path: /dashboard/offers
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@index
  methods:
    - GET
  permission: OfferModule

sort:
  path: /dashboard/offers/sort
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@sort
  methods:
    - GET
  permission: OfferModule

ajax:
  path: /dashboard/offers/ajax
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@ajax
  methods:
    - POST
  permission: OfferModule

create:
  path: /dashboard/offers/create
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@create
  methods:
    - GET
  permission: OfferModule.add

store:
  path: /dashboard/offers/store
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@store
  methods:
    - POST
  permission: OfferModule.add

edit:
  path: /dashboard/offers/{{offer}}/edit
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@edit
  methods:
    - GET
  permission: OfferModule.edit

update:
  path: /dashboard/offers/{{offer}}
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@update
  methods:
    - PUT
    - PATCH
  permission: OfferModule.edit

destroy:
  path: /dashboard/offers/{{offer}}
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@destroy
  methods:
    - DELETE
  permission: OfferModule.delete

saveOrder:
  path: /dashboard/offers/saveOrder
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@saveOrder
  methods:
    - POST
  permission: OfferModule.edit

statuses:
  path: /dashboard/offers/statuses
  controller: Selene\Modules\OfferModule\Http\Controllers\OfferController@statuses
  methods:
    - GET
  permission: OfferModule